spring.application.name=vmall_home
spring.datasource.url=jdbc:mysql://localhost:3306/vmall?characterEncoding=UTF-8&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=778105
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver